/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/patiencenkurumeh/.choosenim/toolchains/nim-0.18.0/lib -o /Users/patiencenkurumeh/Other/kernel/c/nimcache/nake_nakelib.o /Users/patiencenkurumeh/Other/kernel/c/nimcache/nake_nakelib.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw;
typedef struct tySequence_hxqtRaE4Ysj9aFEpaPwKTLg tySequence_hxqtRaE4Ysj9aFEpaPwKTLg;
typedef struct tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_2uzTbg8jwom7zHhmM2RgHg tyTuple_2uzTbg8jwom7zHhmM2RgHg;
typedef struct tyObject_Env_slashUsersslashpatiencenkurumehslashdotnimbleslashpkgsslashnakeminus1dot9dot2slashnakelibdotnim__sO5O0Qy9bzKs0atwA6HUBAw tyObject_Env_slashUsersslashpatiencenkurumehslashdotnimbleslashpkgsslashnakeminus1dot9dot2slashnakelibdotnim__sO5O0Qy9bzKs0atwA6HUBAw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_XOVT24GHXwqiEj5GCsEGCA tyTuple_XOVT24GHXwqiEj5GCsEGCA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyTuple_zfQXUQna33jJINR86AHwAA tyTuple_zfQXUQna33jJINR86AHwAA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw {
tySequence_hxqtRaE4Ysj9aFEpaPwKTLg* data;
NI counter;
NI first;
NI last;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ {
NimStringDesc* desc;
tyProc_IIomJ6ptE6vfJ5zRbATgkQ action;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple_2uzTbg8jwom7zHhmM2RgHg {
void* Field0;
tyObject_Env_slashUsersslashpatiencenkurumehslashdotnimbleslashpkgsslashnakeminus1dot9dot2slashnakelibdotnim__sO5O0Qy9bzKs0atwA6HUBAw* Field1;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tySet_tyEnum_ProcessOption_bnU6W8LhTMnT4JaSWtGlSA;
struct tyTuple_XOVT24GHXwqiEj5GCsEGCA {
NimStringDesc* Field0;
NI Field1;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef N_CLOSURE_PTR(void, TM_60luX1ZawLNwN9bU7RKk1CQ_16) (void);
struct tyTuple_zfQXUQna33jJINR86AHwAA {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* Field3;
};
typedef NimStringDesc* tyArray_24KAM9afIUgUaqBaEBB6r9bg[3];
typedef N_CLOSURE_PTR(void, TM_60luX1ZawLNwN9bU7RKk1CQ_22) (void* ClE_0);
struct tyObject_Env_slashUsersslashpatiencenkurumehslashdotnimbleslashpkgsslashnakeminus1dot9dot2slashnakelibdotnim__sO5O0Qy9bzKs0atwA6HUBAw {
  RootObj Sup;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_hxqtRaE4Ysj9aFEpaPwKTLg {
  TGenericSeq Sup;
  tyTuple_zfQXUQna33jJINR86AHwAA data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_mOcYWTFGHj53uDfDbMKFlQ)(void* p, NI op);
static N_NIMCALL(void, TM_60luX1ZawLNwN9bU7RKk1CQ_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable_k7hKEl26HFSwsVjqnEnpaw)(NI initialSize, tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* Result);
static N_NIMCALL(void, TM_60luX1ZawLNwN9bU7RKk1CQ_5)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, findExe_XcLgn9booQ6akyBsF074Lfw)(NimStringDesc* exe, NIM_BOOL followSymlinks, NimStringDesc** extensions, NI extensionsLen_0);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nospquoteShell)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, askShellCMD_jNCdB8k9a3ai9a9adblax0K8A)(NimStringDesc* cmd);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLineFromStdin_zF3YvaEYDchtz09acJnrLlg)(NimStringDesc* prompt);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(NI, nosexecShellCmd)(NimStringDesc* command);
N_LIB_PRIVATE N_NIMCALL(void, askSilentShellCMD_TfVhU8C1tV7PdCg1kRXy7w)(NimStringDesc* cmd, tyTuple_XOVT24GHXwqiEj5GCsEGCA* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, execCmdEx_bITTGyMXZwwEXI9blfpV4cg)(NimStringDesc* command, tySet_tyEnum_ProcessOption_bnU6W8LhTMnT4JaSWtGlSA options, tyTuple_XOVT24GHXwqiEj5GCsEGCA* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shell_ee9aOKBqwQqdhEEqS5TF5zw)(NimStringDesc** cmd, NI cmdLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, direShell_ee9aOKBqwQqdhEEqS5TF5zw_2)(NimStringDesc** cmd, NI cmdLen_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, silentShell_SJc1LNzGqudXPJQHaW0F9aA)(NimStringDesc* info, NimStringDesc** cmd, NI cmdLen_0);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, direSilentShell_SJc1LNzGqudXPJQHaW0F9aA_2)(NimStringDesc* info, NimStringDesc** cmd, NI cmdLen_0);
static N_INLINE(void, cd_bpYZkT8FGvsBBJMVXhfIAgnakelib)(NimStringDesc* dir);
static N_INLINE(void, setCurrentDir_JEua7nd6wiRPKhcry7jtHQosproc)(NimStringDesc* newDir);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, needsRefresh_QHhirGNQobIaUADnTn0zUA)(NimStringDesc* target, NimStringDesc** src, NI srcLen_0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(NF, toSeconds_Gg29bvJbPEnFoG9aNRGMxIFw)(NI64 time_0);
N_LIB_PRIVATE N_NIMCALL(NI64, nosgetLastModificationTime)(NimStringDesc* file);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*, newNakeTask_HQTtPOlr71CsKbAYsa6rzA)(NimStringDesc* desc, tyProc_IIomJ6ptE6vfJ5zRbATgkQ action);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib)(NimStringDesc* name);
N_LIB_PRIVATE N_NIMCALL(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ**, X5BX5D__Rw1kWL89b9cIfwlYQrz9aubEg)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, listTasksImpl_L4A9b0Ix4poykTbyouwn9bMQ)(void);
static N_INLINE(NI, len_fqRbcPA9bMJMjX1d9ahv9cfvQnakelib)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_NIMCALL(void, TM_60luX1ZawLNwN9bU7RKk1CQ_21)(void);
static N_INLINE(NI, rawGet_qiKnmqBc9bRXEoz6fzVlrlwtables)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, subInt)(NI a, NI b);
tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw tasks_0HJ5yIgo9cGesh26QXOOfNA;
TNimType NTI_EVByvQPvrJpkNP7FerfjWQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_IIomJ6ptE6vfJ5zRbATgkQ_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_58EFneeS9at7cA541QCoGAw_;
TNimType NTI_mOcYWTFGHj53uDfDbMKFlQ_;
extern TNimType NTI_e8qz3X6b0xRqpuWSd9blZAw_;
NIM_BOOL validateShellCommands_quwzqIS8fAX3xw9cg3E8HOA;
NimStringDesc* nimExe_qLiX9cTsgIpZCJ9csTBPn5Vw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_XOVT24GHXwqiEj5GCsEGCA_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_3XwRQvmzCEOC4QnT706q1g_;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
tyProc_IIomJ6ptE6vfJ5zRbATgkQ listTasks_M8dIlirl4Mn7pRwSAFG7cA;
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_6, "nim", 3);
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_8, "", 0);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_60luX1ZawLNwN9bU7RKk1CQ_7 = {((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_8)}
;
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_9, "nimrod", 6);
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_10, "Run\? `$#` [N/y]\012", 16);
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_11, "not isNil(cmd) ", 15);
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_12, " ", 1);
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_13, "\0120 < len(src) Pass some parameters to check for", 47);
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_17, "\0120 < len(tasks) ", 16);
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_19, "Available tasks:", 16);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_60luX1ZawLNwN9bU7RKk1CQ_18 = {((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_19)}
;
STRING_LITERAL(TM_60luX1ZawLNwN9bU7RKk1CQ_20, " - ", 3);
static N_NIMCALL(void, Marker_tyRef_mOcYWTFGHj53uDfDbMKFlQ)(void* p, NI op) {
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* a;
	a = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*)p;
	nimGCvisit((void*)(*a).desc, op);
	nimGCvisit((void*)(*a).action.ClE_0, op);
}
static N_NIMCALL(void, TM_60luX1ZawLNwN9bU7RKk1CQ_4)(void) {
	nimGCvisit((void*)tasks_0HJ5yIgo9cGesh26QXOOfNA.data, 0);
}
static N_NIMCALL(void, TM_60luX1ZawLNwN9bU7RKk1CQ_5)(void) {
	nimGCvisit((void*)nimExe_qLiX9cTsgIpZCJ9csTBPn5Vw, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, askShellCMD_jNCdB8k9a3ai9a9adblax0K8A)(NimStringDesc* cmd) {
	NIM_BOOL result;
	nimfr_("askShellCMD", "nakelib.nim");
{	result = (NIM_BOOL)0;
	nimln_(73, "nakelib.nim");
	{
		NimStringDesc* ans;
		NimStringDesc* T5_;
		if (!validateShellCommands_quwzqIS8fAX3xw9cg3E8HOA) goto LA3_;
		nimln_(74, "nakelib.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = nsuFormatSingleElem(((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_10), cmd);
		ans = readLineFromStdin_zF3YvaEYDchtz09acJnrLlg(T5_);
		nimln_(75, "nakelib.nim");
		{
			NI T10_;
			if ((NU)(((NI) 0)) > (NU)(ans->Sup.len)) raiseIndexError();
			if (!(((NU8)(ans->data[((NI) 0)])) == ((NU8)(121)) || ((NU8)(ans->data[((NI) 0)])) == ((NU8)(89)))) goto LA8_;
			nimln_(76, "nakelib.nim");
			T10_ = (NI)0;
			T10_ = nosexecShellCmd(cmd);
			result = (T10_ == ((NI) 0));
		}
		goto LA6_;
		LA8_: ;
		{
			nimln_(78, "nakelib.nim");
			result = NIM_FALSE;
			goto BeforeRet_;
		}
		LA6_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		NI T13_;
		nimln_(80, "nakelib.nim");
		T13_ = (NI)0;
		T13_ = nosexecShellCmd(cmd);
		result = (T13_ == ((NI) 0));
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, askSilentShellCMD_TfVhU8C1tV7PdCg1kRXy7w)(NimStringDesc* cmd, tyTuple_XOVT24GHXwqiEj5GCsEGCA* Result) {
	nimfr_("askSilentShellCMD", "nakelib.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_XOVT24GHXwqiEj5GCsEGCA_));
	nimln_(90, "nakelib.nim");
	{
		if (!!(!((cmd == 0)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_11));
	}
	LA3_: ;
	nimln_(92, "nakelib.nim");
	{
		NimStringDesc* ans;
		NimStringDesc* T9_;
		if (!validateShellCommands_quwzqIS8fAX3xw9cg3E8HOA) goto LA7_;
		nimln_(93, "nakelib.nim");
		T9_ = (NimStringDesc*)0;
		T9_ = nsuFormatSingleElem(((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_10), cmd);
		ans = readLineFromStdin_zF3YvaEYDchtz09acJnrLlg(T9_);
		nimln_(94, "nakelib.nim");
		{
			if ((NU)(((NI) 0)) > (NU)(ans->Sup.len)) raiseIndexError();
			if (!(((NU8)(ans->data[((NI) 0)])) == ((NU8)(121)) || ((NU8)(ans->data[((NI) 0)])) == ((NU8)(89)))) goto LA12_;
			nimln_(95, "nakelib.nim");
			execCmdEx_bITTGyMXZwwEXI9blfpV4cg(cmd, 10, Result);
		}
		goto LA10_;
		LA12_: ;
		{
			nimln_(97, "nakelib.nim");
			unsureAsgnRef((void**) (&(*Result).Field0), copyString(((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_8)));
			nimln_(98, "nakelib.nim");
			(*Result).Field1 = ((NI) -1);
		}
		LA10_: ;
	}
	goto LA5_;
	LA7_: ;
	{
		nimln_(100, "nakelib.nim");
		execCmdEx_bITTGyMXZwwEXI9blfpV4cg(cmd, 10, Result);
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shell_ee9aOKBqwQqdhEEqS5TF5zw)(NimStringDesc** cmd, NI cmdLen_0) {
	NIM_BOOL result;
	NimStringDesc* T1_;
	nimfr_("shell", "nakelib.nim");
	result = (NIM_BOOL)0;
	nimln_(112, "nakelib.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = nsuJoinSep(cmd, cmdLen_0, ((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_12));
	result = askShellCMD_jNCdB8k9a3ai9a9adblax0K8A(T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, direShell_ee9aOKBqwQqdhEEqS5TF5zw_2)(NimStringDesc** cmd, NI cmdLen_0) {
	NIM_BOOL result;
	nimfr_("direShell", "nakelib.nim");
	result = (NIM_BOOL)0;
	nimln_(122, "nakelib.nim");
	result = shell_ee9aOKBqwQqdhEEqS5TF5zw(cmd, cmdLen_0);
	nimln_(123, "nakelib.nim");
	{
		if (!!(result)) goto LA3_;
		exit(((NI) 1));
	}
	LA3_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, silentShell_SJc1LNzGqudXPJQHaW0F9aA)(NimStringDesc* info, NimStringDesc** cmd, NI cmdLen_0) {
	NIM_BOOL result;
	NimStringDesc* T6_;
	tyTuple_XOVT24GHXwqiEj5GCsEGCA T7_;
	NimStringDesc* output;
	NI exitCode;
	nimfr_("silentShell", "nakelib.nim");
	result = (NIM_BOOL)0;
	nimln_(147, "nakelib.nim");
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T5_;
		if (!!((info == 0))) goto LA3_;
		nimln_(148, "nakelib.nim");
		memset((void*)T5_, 0, sizeof(T5_));
		T5_[0] = copyString(info);
		echoBinSafe(T5_, 1);
	}
	LA3_: ;
	nimln_(149, "nakelib.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = nsuJoinSep(cmd, cmdLen_0, ((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_12));
	memset((void*)(&T7_), 0, sizeof(T7_));
	askSilentShellCMD_TfVhU8C1tV7PdCg1kRXy7w(T6_, (&T7_));
	output = (NimStringDesc*)0;
	output = T7_.Field0;
	exitCode = (NI)0;
	exitCode = T7_.Field1;
	nimln_(150, "nakelib.nim");
	result = (((NI) 0) == exitCode);
	nimln_(151, "nakelib.nim");
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T12_;
		if (!!(result)) goto LA10_;
		nimln_(152, "nakelib.nim");
		memset((void*)T12_, 0, sizeof(T12_));
		T12_[0] = copyString(output);
		echoBinSafe(T12_, 1);
	}
	LA10_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, direSilentShell_SJc1LNzGqudXPJQHaW0F9aA_2)(NimStringDesc* info, NimStringDesc** cmd, NI cmdLen_0) {
	NIM_BOOL result;
	nimfr_("direSilentShell", "nakelib.nim");
	result = (NIM_BOOL)0;
	nimln_(167, "nakelib.nim");
	result = silentShell_SJc1LNzGqudXPJQHaW0F9aA(info, cmd, cmdLen_0);
	nimln_(168, "nakelib.nim");
	{
		if (!!(result)) goto LA3_;
		exit(((NI) 1));
	}
	LA3_: ;
	popFrame();
	return result;
}

static N_INLINE(void, setCurrentDir_JEua7nd6wiRPKhcry7jtHQosproc)(NimStringDesc* newDir) {
	nimfr_("setCurrentDir", "os.nim");
	nimln_(287, "os.nim");
	{
		int T3_;
		NI32 T6_;
		nimln_(398, "system.nim");
		nimln_(287, "os.nim");
		T3_ = (int)0;
		T3_ = chdir(newDir->data);
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_8));
	}
	LA4_: ;
	popFrame();
}

static N_INLINE(void, cd_bpYZkT8FGvsBBJMVXhfIAgnakelib)(NimStringDesc* dir) {
	nimfr_("cd", "nakelib.nim");
	nimln_(178, "nakelib.nim");
	setCurrentDir_JEua7nd6wiRPKhcry7jtHQosproc(dir);
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim");
	result = (Exception*)0;
	nimln_(3350, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, needsRefresh_QHhirGNQobIaUADnTn0zUA)(NimStringDesc* target, NimStringDesc** src, NI srcLen_0) {
	NIM_BOOL result;
	NF volatile targetTime;
	TSafePoint TM_60luX1ZawLNwN9bU7RKk1CQ_14;
	nimfr_("needsRefresh", "nakelib.nim");
{	result = (NIM_BOOL)0;
	nimln_(216, "nakelib.nim");
	{
		if (!!((((NI) 0) < srcLen_0))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_13));
	}
	LA3_: ;
	targetTime = (NF)0;
	nimln_(218, "nakelib.nim");
	pushSafePoint(&TM_60luX1ZawLNwN9bU7RKk1CQ_14);
	TM_60luX1ZawLNwN9bU7RKk1CQ_14.status = _setjmp(TM_60luX1ZawLNwN9bU7RKk1CQ_14.context);
	if (TM_60luX1ZawLNwN9bU7RKk1CQ_14.status == 0) {
		NI64 T6_;
		nimln_(219, "nakelib.nim");
		T6_ = (NI64)0;
		T6_ = nosgetLastModificationTime(target);
		targetTime = toSeconds_Gg29bvJbPEnFoG9aNRGMxIFw(T6_);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI_3XwRQvmzCEOC4QnT706q1g_))) {
			TM_60luX1ZawLNwN9bU7RKk1CQ_14.status = 0;
			nimln_(221, "nakelib.nim");
			result = NIM_TRUE;
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
		}
	}
	if (TM_60luX1ZawLNwN9bU7RKk1CQ_14.status != 0) reraiseException();
	{
		NimStringDesc* s;
		NI i;
		s = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NF srcTime;
				NI64 T12_;
				NI TM_60luX1ZawLNwN9bU7RKk1CQ_15;
				if (!(i < srcLen_0)) goto LA11;
				nimln_(2187, "system.nim");
				if ((NU)(i) >= (NU)(srcLen_0)) raiseIndexError();
				s = src[i];
				nimln_(224, "nakelib.nim");
				T12_ = (NI64)0;
				T12_ = nosgetLastModificationTime(s);
				srcTime = toSeconds_Gg29bvJbPEnFoG9aNRGMxIFw(T12_);
				nimln_(225, "nakelib.nim");
				{
					if (!(targetTime < srcTime)) goto LA15_;
					nimln_(226, "nakelib.nim");
					result = NIM_TRUE;
					goto BeforeRet_;
				}
				LA15_: ;
				nimln_(2188, "system.nim");
				TM_60luX1ZawLNwN9bU7RKk1CQ_15 = addInt(i, ((NI) 1));
				i = (NI)(TM_60luX1ZawLNwN9bU7RKk1CQ_15);
			} LA11: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*, newNakeTask_HQTtPOlr71CsKbAYsa6rzA)(NimStringDesc* desc, tyProc_IIomJ6ptE6vfJ5zRbATgkQ action) {
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* result;
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* T1_;
	NimStringDesc* T2_;
	nimfr_("newNakeTask", "nakelib.nim");
	result = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*)0;
	nimln_(230, "nakelib.nim");
	T1_ = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*)0;
	T1_ = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*) newObj((&NTI_mOcYWTFGHj53uDfDbMKFlQ_), sizeof(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ));
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).desc; (*T1_).desc = copyStringRC1(desc);
	if (T2_) nimGCunrefNoCycle(T2_);
	asgnRef((void**) (&(*T1_).action.ClE_0), action.ClE_0);
	(*T1_).action.ClP_0 = action.ClP_0;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(void, runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib)(NimStringDesc* name) {
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ** T1_;
	nimfr_("runTask", "nakelib.nim");
	nimln_(252, "nakelib.nim");
	T1_ = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ**)0;
	T1_ = X5BX5D__Rw1kWL89b9cIfwlYQrz9aubEg((&tasks_0HJ5yIgo9cGesh26QXOOfNA), name);
	(*(*T1_)).action.ClE_0? (*(*T1_)).action.ClP_0((*(*T1_)).action.ClE_0):((TM_60luX1ZawLNwN9bU7RKk1CQ_16)((*(*T1_)).action.ClP_0))();
	popFrame();
}

static N_INLINE(NI, len_fqRbcPA9bMJMjX1d9ahv9cfvQnakelib)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t) {
	NI result;
	nimfr_("len", "tables.nim");
	result = (NI)0;
	nimln_(491, "tables.nim");
	result = (*t).counter;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(398, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, listTasksImpl_L4A9b0Ix4poykTbyouwn9bMQ)(void) {
	nimfr_("listTasksImpl", "nakelib.nim");
	nimln_(278, "nakelib.nim");
	{
		NI T3_;
		T3_ = (NI)0;
		T3_ = len_fqRbcPA9bMJMjX1d9ahv9cfvQnakelib((&tasks_0HJ5yIgo9cGesh26QXOOfNA));
		if (!!((((NI) 0) < T3_))) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_17));
	}
	LA4_: ;
	nimln_(279, "nakelib.nim");
	echoBinSafe(TM_60luX1ZawLNwN9bU7RKk1CQ_18, 1);
	{
		NimStringDesc* name;
		tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* task;
		NI h;
		name = (NimStringDesc*)0;
		task = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*)0;
		nimln_(504, "tables.nim");
		h = tasks_0HJ5yIgo9cGesh26QXOOfNA.first;
		{
			nimln_(513, "tables.nim");
			while (1) {
				NI nxt;
				nimln_(505, "tables.nim");
				if (!(((NI) 0) <= h)) goto LA8;
				nimln_(506, "tables.nim");
				if ((NU)(h) >= (NU)(tasks_0HJ5yIgo9cGesh26QXOOfNA.data->Sup.len)) raiseIndexError();
				nxt = tasks_0HJ5yIgo9cGesh26QXOOfNA.data->data[h].Field1;
				nimln_(507, "tables.nim");
				{
					NIM_BOOL T11_;
					tyArray_24KAM9afIUgUaqBaEBB6r9bg T14_;
					if ((NU)(h) >= (NU)(tasks_0HJ5yIgo9cGesh26QXOOfNA.data->Sup.len)) raiseIndexError();
					T11_ = (NIM_BOOL)0;
					T11_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(tasks_0HJ5yIgo9cGesh26QXOOfNA.data->data[h].Field0);
					if (!T11_) goto LA12_;
					nimln_(514, "tables.nim");
					if ((NU)(h) >= (NU)(tasks_0HJ5yIgo9cGesh26QXOOfNA.data->Sup.len)) raiseIndexError();
					name = tasks_0HJ5yIgo9cGesh26QXOOfNA.data->data[h].Field2;
					if ((NU)(h) >= (NU)(tasks_0HJ5yIgo9cGesh26QXOOfNA.data->Sup.len)) raiseIndexError();
					task = tasks_0HJ5yIgo9cGesh26QXOOfNA.data->data[h].Field3;
					nimln_(281, "nakelib.nim");
					memset((void*)T14_, 0, sizeof(T14_));
					T14_[0] = copyString(name);
					T14_[1] = copyString(((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_20));
					T14_[2] = copyString((*task).desc);
					echoBinSafe(T14_, 3);
				}
				LA12_: ;
				nimln_(508, "tables.nim");
				h = nxt;
			} LA8: ;
		}
	}
	popFrame();
}
static N_NIMCALL(void, TM_60luX1ZawLNwN9bU7RKk1CQ_21)(void) {
	nimGCvisit((void*)listTasks_M8dIlirl4Mn7pRwSAFG7cA.ClE_0, 0);
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_60luX1ZawLNwN9bU7RKk1CQ_23;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_60luX1ZawLNwN9bU7RKk1CQ_23 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_60luX1ZawLNwN9bU7RKk1CQ_23) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_qiKnmqBc9bRXEoz6fzVlrlwtables)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_60luX1ZawLNwN9bU7RKk1CQ_24;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T11_ = ((*t).data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T11_ = eqStrings((*t).data->data[h].Field2, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_60luX1ZawLNwN9bU7RKk1CQ_24 = subInt(((NI) -1), h);
	result = (NI)(TM_60luX1ZawLNwN9bU7RKk1CQ_24);
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, nake_nakelibInit000)(void) {
	tyProc_IIomJ6ptE6vfJ5zRbATgkQ T5_;
	nimfr_("nakelib", "nakelib.nim");
nimRegisterGlobalMarker(TM_60luX1ZawLNwN9bU7RKk1CQ_4);
nimRegisterGlobalMarker(TM_60luX1ZawLNwN9bU7RKk1CQ_5);
nimRegisterGlobalMarker(TM_60luX1ZawLNwN9bU7RKk1CQ_21);
	nimln_(36, "nakelib.nim");
	initOrderedTable_k7hKEl26HFSwsVjqnEnpaw(((NI) 32), (&tasks_0HJ5yIgo9cGesh26QXOOfNA));
	nimln_(41, "nakelib.nim");
	validateShellCommands_quwzqIS8fAX3xw9cg3E8HOA = NIM_FALSE;
	nimln_(66, "nakelib.nim");
	asgnRefNoCycle((void**) (&nimExe_qLiX9cTsgIpZCJ9csTBPn5Vw), findExe_XcLgn9booQ6akyBsF074Lfw(((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_6), NIM_TRUE, TM_60luX1ZawLNwN9bU7RKk1CQ_7, 1));
	nimln_(67, "nakelib.nim");
	{
		if (!((nimExe_qLiX9cTsgIpZCJ9csTBPn5Vw ? nimExe_qLiX9cTsgIpZCJ9csTBPn5Vw->Sup.len : 0) < ((NI) 1))) goto LA3_;
		nimln_(68, "nakelib.nim");
		asgnRefNoCycle((void**) (&nimExe_qLiX9cTsgIpZCJ9csTBPn5Vw), findExe_XcLgn9booQ6akyBsF074Lfw(((NimStringDesc*) &TM_60luX1ZawLNwN9bU7RKk1CQ_9), NIM_TRUE, TM_60luX1ZawLNwN9bU7RKk1CQ_7, 1));
	}
	LA3_: ;
	nimln_(69, "nakelib.nim");
	asgnRefNoCycle((void**) (&nimExe_qLiX9cTsgIpZCJ9csTBPn5Vw), nospquoteShell(nimExe_qLiX9cTsgIpZCJ9csTBPn5Vw));
	nimln_(284, "nakelib.nim");
	memset((void*)(&T5_), 0, sizeof(T5_));
	T5_.ClP_0 = ((TM_60luX1ZawLNwN9bU7RKk1CQ_22) (listTasksImpl_L4A9b0Ix4poykTbyouwn9bMQ)); T5_.ClE_0 = NIM_NIL;
	asgnRef((void**) (&listTasks_M8dIlirl4Mn7pRwSAFG7cA.ClE_0), T5_.ClE_0);
	listTasks_M8dIlirl4Mn7pRwSAFG7cA.ClP_0 = T5_.ClP_0;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nake_nakelibDatInit000)(void) {
static TNimNode* TM_60luX1ZawLNwN9bU7RKk1CQ_2[2];
static TNimNode* TM_60luX1ZawLNwN9bU7RKk1CQ_3[2];
static TNimNode TM_60luX1ZawLNwN9bU7RKk1CQ_0[6];
NTI_EVByvQPvrJpkNP7FerfjWQ_.size = sizeof(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ);
NTI_EVByvQPvrJpkNP7FerfjWQ_.kind = 18;
NTI_EVByvQPvrJpkNP7FerfjWQ_.base = 0;
TM_60luX1ZawLNwN9bU7RKk1CQ_2[0] = &TM_60luX1ZawLNwN9bU7RKk1CQ_0[1];
TM_60luX1ZawLNwN9bU7RKk1CQ_0[1].kind = 1;
TM_60luX1ZawLNwN9bU7RKk1CQ_0[1].offset = offsetof(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ, desc);
TM_60luX1ZawLNwN9bU7RKk1CQ_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_60luX1ZawLNwN9bU7RKk1CQ_0[1].name = "desc";
TM_60luX1ZawLNwN9bU7RKk1CQ_2[1] = &TM_60luX1ZawLNwN9bU7RKk1CQ_0[2];
NTI_IIomJ6ptE6vfJ5zRbATgkQ_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_IIomJ6ptE6vfJ5zRbATgkQ_.kind = 18;
NTI_IIomJ6ptE6vfJ5zRbATgkQ_.base = 0;
TM_60luX1ZawLNwN9bU7RKk1CQ_3[0] = &TM_60luX1ZawLNwN9bU7RKk1CQ_0[4];
TM_60luX1ZawLNwN9bU7RKk1CQ_0[4].kind = 1;
TM_60luX1ZawLNwN9bU7RKk1CQ_0[4].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_60luX1ZawLNwN9bU7RKk1CQ_0[4].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_60luX1ZawLNwN9bU7RKk1CQ_0[4].name = "Field0";
TM_60luX1ZawLNwN9bU7RKk1CQ_3[1] = &TM_60luX1ZawLNwN9bU7RKk1CQ_0[5];
TM_60luX1ZawLNwN9bU7RKk1CQ_0[5].kind = 1;
TM_60luX1ZawLNwN9bU7RKk1CQ_0[5].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_60luX1ZawLNwN9bU7RKk1CQ_0[5].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_60luX1ZawLNwN9bU7RKk1CQ_0[5].name = "Field1";
TM_60luX1ZawLNwN9bU7RKk1CQ_0[3].len = 2; TM_60luX1ZawLNwN9bU7RKk1CQ_0[3].kind = 2; TM_60luX1ZawLNwN9bU7RKk1CQ_0[3].sons = &TM_60luX1ZawLNwN9bU7RKk1CQ_3[0];
NTI_IIomJ6ptE6vfJ5zRbATgkQ_.node = &TM_60luX1ZawLNwN9bU7RKk1CQ_0[3];
TM_60luX1ZawLNwN9bU7RKk1CQ_0[2].kind = 1;
TM_60luX1ZawLNwN9bU7RKk1CQ_0[2].offset = offsetof(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ, action);
TM_60luX1ZawLNwN9bU7RKk1CQ_0[2].typ = (&NTI_IIomJ6ptE6vfJ5zRbATgkQ_);
TM_60luX1ZawLNwN9bU7RKk1CQ_0[2].name = "action";
TM_60luX1ZawLNwN9bU7RKk1CQ_0[0].len = 2; TM_60luX1ZawLNwN9bU7RKk1CQ_0[0].kind = 2; TM_60luX1ZawLNwN9bU7RKk1CQ_0[0].sons = &TM_60luX1ZawLNwN9bU7RKk1CQ_2[0];
NTI_EVByvQPvrJpkNP7FerfjWQ_.node = &TM_60luX1ZawLNwN9bU7RKk1CQ_0[0];
NTI_mOcYWTFGHj53uDfDbMKFlQ_.size = sizeof(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*);
NTI_mOcYWTFGHj53uDfDbMKFlQ_.kind = 22;
NTI_mOcYWTFGHj53uDfDbMKFlQ_.base = (&NTI_EVByvQPvrJpkNP7FerfjWQ_);
NTI_mOcYWTFGHj53uDfDbMKFlQ_.marker = Marker_tyRef_mOcYWTFGHj53uDfDbMKFlQ;
}

