/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/patiencenkurumeh/.choosenim/toolchains/nim-0.18.0/lib -o /Users/patiencenkurumeh/Other/kernel/c/nimcache/nake_nake.o /Users/patiencenkurumeh/Other/kernel/c/nimcache/nake_nake.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw;
typedef struct tySequence_hxqtRaE4Ysj9aFEpaPwKTLg tySequence_hxqtRaE4Ysj9aFEpaPwKTLg;
typedef struct tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ;
typedef struct tyTuple_zfQXUQna33jJINR86AHwAA tyTuple_zfQXUQna33jJINR86AHwAA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w {
  RootObj Sup;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmd;
NI pos;
NimStringDesc* remainingShortOptions;
tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind;
NimStringDesc* key;
NimStringDesc* val;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw {
tySequence_hxqtRaE4Ysj9aFEpaPwKTLg* data;
NI counter;
NI first;
NI last;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
typedef N_CLOSURE_PTR(void, TM_IkED2ymoJCpNKBOD8YpaOw_11) (void);
struct tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ {
NimStringDesc* desc;
tyProc_IIomJ6ptE6vfJ5zRbATgkQ action;
};
typedef N_CLOSURE_PTR(void, TM_IkED2ymoJCpNKBOD8YpaOw_12) (void);
struct tyTuple_zfQXUQna33jJINR86AHwAA {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* Field3;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_hxqtRaE4Ysj9aFEpaPwKTLg {
  TGenericSeq Sup;
  tyTuple_zfQXUQna33jJINR86AHwAA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NOCONV(void, moduleHook_9crUDuZr3tuPgOCt7jrrGjA)(void);
N_LIB_PRIVATE N_NIMCALL(void, initOptParser_7ywjeToZhKr9cLpneviH7zg)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_LIB_PRIVATE N_NIMCALL(void, npo2next)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_oT1eh19cHM6fzpWOLezWq9aw)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, NimStringDesc* key);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib)(NimStringDesc* name);
N_LIB_PRIVATE N_NIMCALL(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ**, X5BX5D__Rw1kWL89b9cIfwlYQrz9aubEg)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, NimStringDesc* key);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet_a79cAy655TpaxcmIcfQyChg)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, NimStringDesc* key, NI* hc);
extern TNimType NTI_w3uFmxpwEmgEXFUJjUl10w_;
extern NIM_BOOL validateShellCommands_quwzqIS8fAX3xw9cg3E8HOA;
extern tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw tasks_0HJ5yIgo9cGesh26QXOOfNA;
extern tyProc_IIomJ6ptE6vfJ5zRbATgkQ listTasks_M8dIlirl4Mn7pRwSAFG7cA;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_IkED2ymoJCpNKBOD8YpaOw_2, "careful", 7);
STRING_LITERAL(TM_IkED2ymoJCpNKBOD8YpaOw_3, "c", 1);
STRING_LITERAL(TM_IkED2ymoJCpNKBOD8YpaOw_4, "tasks", 5);
STRING_LITERAL(TM_IkED2ymoJCpNKBOD8YpaOw_5, "t", 1);
STRING_LITERAL(TM_IkED2ymoJCpNKBOD8YpaOw_6, "default", 7);
STRING_LITERAL(TM_IkED2ymoJCpNKBOD8YpaOw_8, "No task specified, running default task defined by nakefile.", 60);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_IkED2ymoJCpNKBOD8YpaOw_7 = {((NimStringDesc*) &TM_IkED2ymoJCpNKBOD8YpaOw_8)}
;
STRING_LITERAL(TM_IkED2ymoJCpNKBOD8YpaOw_9, "Task \'", 6);
STRING_LITERAL(TM_IkED2ymoJCpNKBOD8YpaOw_10, "\' not found.", 12);

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib)(NimStringDesc* name) {
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ** T1_;
	nimfr_("runTask", "nakelib.nim");
	nimln_(252, "nakelib.nim");
	T1_ = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ**)0;
	T1_ = X5BX5D__Rw1kWL89b9cIfwlYQrz9aubEg((&tasks_0HJ5yIgo9cGesh26QXOOfNA), name);
	(*(*T1_)).action.ClE_0? (*(*T1_)).action.ClP_0((*(*T1_)).action.ClE_0):((TM_IkED2ymoJCpNKBOD8YpaOw_12)((*(*T1_)).action.ClP_0))();
	popFrame();
}

N_LIB_PRIVATE N_NOCONV(void, moduleHook_9crUDuZr3tuPgOCt7jrrGjA)(void) {
	NimStringDesc* task;
	NIM_BOOL printTaskList;
	NIM_BOOL badTask;
	NIM_BOOL T19_;
	NIM_BOOL T21_;
	nimfr_("moduleHook", "nake.nim");
	task = (NimStringDesc*)0;
	printTaskList = (NIM_BOOL)0;
	{
		tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind;
		NimStringDesc* key;
		NimStringDesc* val;
		tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w p;
		kind = (tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw)0;
		key = (NimStringDesc*)0;
		val = (NimStringDesc*)0;
		memset((void*)(&p), 0, sizeof(p));
		p.Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
		nimln_(162, "parseopt2.nim");
		initOptParser_7ywjeToZhKr9cLpneviH7zg((&p));
		{
			nimln_(163, "parseopt2.nim");
			while (1) {
				nimln_(164, "parseopt2.nim");
				npo2next((&p));
				nimln_(165, "parseopt2.nim");
				{
					if (!(p.kind == ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 0))) goto LA6_;
					goto LA2;
				}
				LA6_: ;
				nimln_(166, "parseopt2.nim");
				kind = p.kind;
				key = p.key;
				val = p.val;
				nimln_(71, "nake.nim");
				switch (kind) {
				case ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 2):
				case ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 3):
				{
					NimStringDesc* T9_;
					nimln_(73, "nake.nim");
					T9_ = (NimStringDesc*)0;
					T9_ = nsuToLowerAsciiStr(key);
					if (eqStrings(T9_, ((NimStringDesc*) &TM_IkED2ymoJCpNKBOD8YpaOw_2))) goto LA10_;
					if (eqStrings(T9_, ((NimStringDesc*) &TM_IkED2ymoJCpNKBOD8YpaOw_3))) goto LA10_;
					if (eqStrings(T9_, ((NimStringDesc*) &TM_IkED2ymoJCpNKBOD8YpaOw_4))) goto LA11_;
					if (eqStrings(T9_, ((NimStringDesc*) &TM_IkED2ymoJCpNKBOD8YpaOw_5))) goto LA11_;
					goto LA12_;
					LA10_: ;
					{
						nimln_(75, "nake.nim");
						validateShellCommands_quwzqIS8fAX3xw9cg3E8HOA = NIM_TRUE;
					}
					goto LA13_;
					LA11_: ;
					{
						nimln_(77, "nake.nim");
						printTaskList = NIM_TRUE;
					}
					goto LA13_;
					LA12_: ;
					{
					}
					LA13_: ;
				}
				break;
				case ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 1):
				{
					nimln_(81, "nake.nim");
					task = copyString(key);
					nimln_(82, "nake.nim");
					goto LA1;
				}
				break;
				default:
				{
				}
				break;
				}
			}
		} LA2: ;
	} LA1: ;
	nimln_(85, "nake.nim");
	T19_ = (NIM_BOOL)0;
	T19_ = !((task == 0));
	if (!(T19_)) goto LA20_;
	T21_ = (NIM_BOOL)0;
	T21_ = hasKey_oT1eh19cHM6fzpWOLezWq9aw((&tasks_0HJ5yIgo9cGesh26QXOOfNA), task);
	T19_ = !(T21_);
	LA20_: ;
	badTask = T19_;
	nimln_(86, "nake.nim");
	{
		NIM_BOOL T24_;
		T24_ = (NIM_BOOL)0;
		T24_ = (task == 0);
		if (!(T24_)) goto LA25_;
		T24_ = hasKey_oT1eh19cHM6fzpWOLezWq9aw((&tasks_0HJ5yIgo9cGesh26QXOOfNA), ((NimStringDesc*) &TM_IkED2ymoJCpNKBOD8YpaOw_6));
		LA25_: ;
		if (!T24_) goto LA26_;
		nimln_(87, "nake.nim");
		echoBinSafe(TM_IkED2ymoJCpNKBOD8YpaOw_7, 1);
		nimln_(61, "nakelib.nim");
		task = copyString(((NimStringDesc*) &TM_IkED2ymoJCpNKBOD8YpaOw_6));
	}
	LA26_: ;
	nimln_(89, "nake.nim");
	{
		NIM_BOOL T30_;
		NIM_BOOL T31_;
		NI T42_;
		T30_ = (NIM_BOOL)0;
		T31_ = (NIM_BOOL)0;
		T31_ = printTaskList;
		if (T31_) goto LA32_;
		T31_ = (task == 0);
		LA32_: ;
		T30_ = T31_;
		if (T30_) goto LA33_;
		T30_ = badTask;
		LA33_: ;
		if (!T30_) goto LA34_;
		nimln_(90, "nake.nim");
		{
			tyArray_nHXaesL0DJZHyVS07ARPRA T40_;
			NimStringDesc* T41_;
			if (!badTask) goto LA38_;
			memset((void*)T40_, 0, sizeof(T40_));
			T41_ = (NimStringDesc*)0;
			T41_ = rawNewString(task->Sup.len + 18);
appendString(T41_, ((NimStringDesc*) &TM_IkED2ymoJCpNKBOD8YpaOw_9));
appendString(T41_, task);
appendString(T41_, ((NimStringDesc*) &TM_IkED2ymoJCpNKBOD8YpaOw_10));
			T40_[0] = T41_;
			echoBinSafe(T40_, 1);
		}
		LA38_: ;
		nimln_(91, "nake.nim");
		listTasks_M8dIlirl4Mn7pRwSAFG7cA.ClE_0? listTasks_M8dIlirl4Mn7pRwSAFG7cA.ClP_0(listTasks_M8dIlirl4Mn7pRwSAFG7cA.ClE_0):((TM_IkED2ymoJCpNKBOD8YpaOw_11)(listTasks_M8dIlirl4Mn7pRwSAFG7cA.ClP_0))();
		nimln_(92, "nake.nim");
		T42_ = (NI)0;
		{
			if (!badTask) goto LA45_;
			T42_ = ((NI) 1);
		}
		goto LA43_;
		LA45_: ;
		{
			T42_ = ((NI) 0);
		}
		LA43_: ;
		exit(T42_);
	}
	LA34_: ;
	nimln_(93, "nake.nim");
	runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib(task);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, nake_nakeInit000)(void) {
	nimfr_("nake", "nake.nim");
	nimln_(95, "nake.nim");
	atexit(moduleHook_9crUDuZr3tuPgOCt7jrrGjA);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nake_nakeDatInit000)(void) {
}

