/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/patiencenkurumeh/.choosenim/toolchains/nim-0.18.0/lib -o /Users/patiencenkurumeh/Other/kernel/c/nimcache/nakefile.o /Users/patiencenkurumeh/Other/kernel/c/nimcache/nakefile.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ;
typedef struct tySequence_hxqtRaE4Ysj9aFEpaPwKTLg tySequence_hxqtRaE4Ysj9aFEpaPwKTLg;
typedef struct tyTuple_zfQXUQna33jJINR86AHwAA tyTuple_zfQXUQna33jJINR86AHwAA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw {
tySequence_hxqtRaE4Ysj9aFEpaPwKTLg* data;
NI counter;
NI first;
NI last;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ {
NimStringDesc* desc;
tyProc_IIomJ6ptE6vfJ5zRbATgkQ action;
};
typedef N_CLOSURE_PTR(void, TM_3Dlmt2rJJ9aaakgRfmtnuoQ_9) (void);
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyTuple_zfQXUQna33jJINR86AHwAA {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* Field3;
};
struct tySequence_hxqtRaE4Ysj9aFEpaPwKTLg {
  TGenericSeq Sup;
  tyTuple_zfQXUQna33jJINR86AHwAA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__gh2qirzZ9bR3X9aIeqCUNreg)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, NimStringDesc* key, tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* val);
N_LIB_PRIVATE N_NIMCALL(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*, newNakeTask_HQTtPOlr71CsKbAYsa6rzA)(NimStringDesc* desc, tyProc_IIomJ6ptE6vfJ5zRbATgkQ action);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__m9b1oRdAsL6msR9aJ6HD0RRw)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, nosremoveDir)(NimStringDesc* dir);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__LLbrif9bCFPwWoFgrf9ct4dA)(void* ClE_0);
static N_INLINE(void, runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib)(NimStringDesc* name);
N_LIB_PRIVATE N_NIMCALL(tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ**, X5BX5D__Rw1kWL89b9cIfwlYQrz9aubEg)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringDesc* dir);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__LLbrif9bCFPwWoFgrf9ct4dA_2)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, direShell_ee9aOKBqwQqdhEEqS5TF5zw_2)(NimStringDesc** cmd, NI cmdLen_0);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__LLbrif9bCFPwWoFgrf9ct4dA_3)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_K0B9cBhh9aBKqlA886pvFbpw)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_F6IocCCW9bhHsjIb74qKuqA)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, tySequence_hxqtRaE4Ysj9aFEpaPwKTLg** data, NimStringDesc* key, tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* val, NI hc, NI h);
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC_V5OHZZ1lBqYhTsYT5EEjjA)(tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw* t, NimStringDesc* key, NI hc);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linenoiseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linenoiseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rdstdinInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rdstdinDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nake_nakelibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nake_nakelibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nake_nakeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nake_nakeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, nakefileDatInit000)(void);
extern tyObject_OrderedTable_e8qz3X6b0xRqpuWSd9blZAw tasks_0HJ5yIgo9cGesh26QXOOfNA;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_2, "clean", 5);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_3, "removes build files.", 20);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_5, "bin", 3);
static NIM_CONST tyProc_IIomJ6ptE6vfJ5zRbATgkQ CNSTCLOSURE5 = {colonanonymous__m9b1oRdAsL6msR9aJ6HD0RRw,
NIM_NIL}
;
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_6, "setup", 5);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_7, "creates build directories.", 26);
static NIM_CONST tyProc_IIomJ6ptE6vfJ5zRbATgkQ CNSTCLOSURE9 = {colonanonymous__LLbrif9bCFPwWoFgrf9ct4dA,
NIM_NIL}
;
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_10, "build", 5);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_11, "build the kernel.", 17);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_14, "i686-elf-as", 11);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_15, " src/boot.s -o bin/boot.o", 25);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_3Dlmt2rJJ9aaakgRfmtnuoQ_13 = {((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_14),
((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_15)}
;
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_17, "i686-elf-gcc", 12);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_18, " -T linker.ld -o bin/main.bin -ffreestanding -O2 -nostdlib -Wal"
"l -Wextra bin/*.o src/main.c", 91);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_3Dlmt2rJJ9aaakgRfmtnuoQ_16 = {((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_17),
((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_18)}
;
static NIM_CONST tyProc_IIomJ6ptE6vfJ5zRbATgkQ CNSTCLOSURE13 = {colonanonymous__LLbrif9bCFPwWoFgrf9ct4dA_2,
NIM_NIL}
;
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_19, "run", 3);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_20, "run the kernel using QEMU.", 26);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_22, "bin/main.bin", 12);
STRING_LITERAL(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_24, "qemu-system-i386 -kernel bin/main.bin", 37);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_3Dlmt2rJJ9aaakgRfmtnuoQ_23 = {((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_24)}
;
static NIM_CONST tyProc_IIomJ6ptE6vfJ5zRbATgkQ CNSTCLOSURE22 = {colonanonymous__LLbrif9bCFPwWoFgrf9ct4dA_3,
NIM_NIL}
;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__m9b1oRdAsL6msR9aJ6HD0RRw)(void* ClE_0) {
	nimfr_(":anonymous", "nakelib.nim");
	nimln_(15, "nakefile.nim");
	nosremoveDir(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_5));
	popFrame();
}

static N_INLINE(void, runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib)(NimStringDesc* name) {
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ** T1_;
	nimfr_("runTask", "nakelib.nim");
	nimln_(252, "nakelib.nim");
	T1_ = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ**)0;
	T1_ = X5BX5D__Rw1kWL89b9cIfwlYQrz9aubEg((&tasks_0HJ5yIgo9cGesh26QXOOfNA), name);
	(*(*T1_)).action.ClE_0? (*(*T1_)).action.ClP_0((*(*T1_)).action.ClE_0):((TM_3Dlmt2rJJ9aaakgRfmtnuoQ_9)((*(*T1_)).action.ClP_0))();
	popFrame();
}

N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__LLbrif9bCFPwWoFgrf9ct4dA)(void* ClE_0) {
	nimfr_(":anonymous", "nakelib.nim");
	nimln_(18, "nakefile.nim");
	runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_2));
	nimln_(19, "nakefile.nim");
	noscreateDir(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_5));
	popFrame();
}

N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__LLbrif9bCFPwWoFgrf9ct4dA_2)(void* ClE_0) {
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	nimfr_(":anonymous", "nakelib.nim");
	nimln_(22, "nakefile.nim");
	runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_6));
	nimln_(23, "nakefile.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = direShell_ee9aOKBqwQqdhEEqS5TF5zw_2(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_13, 2);
	nimln_(24, "nakefile.nim");
	T2_ = (NIM_BOOL)0;
	T2_ = direShell_ee9aOKBqwQqdhEEqS5TF5zw_2(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_16, 2);
	popFrame();
}

N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__LLbrif9bCFPwWoFgrf9ct4dA_3)(void* ClE_0) {
	NIM_BOOL T6_;
	nimfr_(":anonymous", "nakelib.nim");
	nimln_(27, "nakefile.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nosexistsFile(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_22));
		if (!!(T3_)) goto LA4_;
		runTask_5SCSFNl9b0DsvZB9aHX2fOUgnakelib(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_10));
	}
	LA4_: ;
	nimln_(28, "nakefile.nim");
	T6_ = (NIM_BOOL)0;
	T6_ = direShell_ee9aOKBqwQqdhEEqS5TF5zw_2(TM_3Dlmt2rJJ9aaakgRfmtnuoQ_23, 1);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_parseopt2DatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_linenoiseDatInit000();
	stdlib_termiosDatInit000();
	stdlib_rdstdinDatInit000();
	stdlib_strtabsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_cpuinfoDatInit000();
	stdlib_kqueueDatInit000();
	stdlib_osprocDatInit000();
	nake_nakelibDatInit000();
	nake_nakeDatInit000();
	nakefileDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_parseopt2Init000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_linenoiseInit000();
	stdlib_termiosInit000();
	stdlib_rdstdinInit000();
	stdlib_strtabsInit000();
	stdlib_streamsInit000();
	stdlib_cpuinfoInit000();
	stdlib_kqueueInit000();
	stdlib_osprocInit000();
	nake_nakelibInit000();
	nake_nakeInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* T1_;
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* T2_;
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* T3_;
	tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ* T4_;
	nimfr_("nakefile", "nakefile.nim");
	nimln_(269, "nakelib.nim");
	nimln_(14, "nakefile.nim");
	T1_ = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*)0;
	T1_ = newNakeTask_HQTtPOlr71CsKbAYsa6rzA(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_3), CNSTCLOSURE5);
	X5BX5Deq__gh2qirzZ9bR3X9aIeqCUNreg((&tasks_0HJ5yIgo9cGesh26QXOOfNA), ((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_2), T1_);
	nimln_(269, "nakelib.nim");
	nimln_(17, "nakefile.nim");
	T2_ = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*)0;
	T2_ = newNakeTask_HQTtPOlr71CsKbAYsa6rzA(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_7), CNSTCLOSURE9);
	X5BX5Deq__gh2qirzZ9bR3X9aIeqCUNreg((&tasks_0HJ5yIgo9cGesh26QXOOfNA), ((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_6), T2_);
	nimln_(269, "nakelib.nim");
	nimln_(21, "nakefile.nim");
	T3_ = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*)0;
	T3_ = newNakeTask_HQTtPOlr71CsKbAYsa6rzA(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_11), CNSTCLOSURE13);
	X5BX5Deq__gh2qirzZ9bR3X9aIeqCUNreg((&tasks_0HJ5yIgo9cGesh26QXOOfNA), ((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_10), T3_);
	nimln_(269, "nakelib.nim");
	nimln_(26, "nakefile.nim");
	T4_ = (tyObject_NakeTaskcolonObjectType__EVByvQPvrJpkNP7FerfjWQ*)0;
	T4_ = newNakeTask_HQTtPOlr71CsKbAYsa6rzA(((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_20), CNSTCLOSURE22);
	X5BX5Deq__gh2qirzZ9bR3X9aIeqCUNreg((&tasks_0HJ5yIgo9cGesh26QXOOfNA), ((NimStringDesc*) &TM_3Dlmt2rJJ9aaakgRfmtnuoQ_19), T4_);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nakefileDatInit000)(void) {
}

